website/auth.py
import os
import secrets
import PIL
from PIL import Image
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort, jsonify, json
from .forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm, VehicleForm, CorporateRegistrationForm
from .models import User, Profession, Country, Province, City, Districts, Town, Areas, Uservehicle, Vehiclemake, Vehiclemakemodel, Vehiclebodytype, Vehiclemodelyear
from werkzeug.security import generate_password_hash, check_password_hash
from website import db, mail
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['POST', 'GET'])
def login():
    if current_user. is_authenticated:
        return redirect(url_for('views.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('views.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(
            form.password.data, method='sha256')
        new_user = User(username=form.username.data,
                        email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        flash(
            f'Your account has been created! Your are now able to login.', 'success')
        return redirect(url_for('auth.login'))

    return render_template('register.html', title='Register', form=form)


def save_picture(form_picture):
    rendon_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = rendon_hex + f_ext
    picture_path = os.path.join(
        auth.root_path, 'static/profile_pics', picture_fn)

    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)
    # form_picture.save(picture_path)

    return picture_fn


@auth.route('/coregister', methods=['GET', 'POST'])
@login_required
def coregister():
    form = CorporateRegistrationForm()
    if form.validate_on_submit():
        if form.img_ntn.data:
            imag_ntn = save_picture(form.img_ntn.data)
            current_user.img_ntn = imag_ntn

        if form.img_logo.data:
            imag_logo = save_picture(form.img_logo.data)
            current_user.img_logo = imag_logo
        current_user.company_name = form.company_name.data
        current_user.mobile = form.mobile.data
        current_user.webpage = form.webpage.data
        current_user.level = "Corporate"
        db.session.commit()
        flash(
            f'Your request has been submited! We well contact you with in 3 working day.', 'success')
        return redirect(url_for('auth.coregister'))
    elif request.method == 'GET':
        form.company_name.data = current_user.company_name
        form.mobile.data = current_user.mobile
        form.webpage.data = current_user.webpage
        form.img_ntn.data = current_user.img_ntn
        form.img_logo.data = current_user.img_logo

    image_ntn = url_for(
        'static', filename='profile_pics/' + current_user.img_ntn)

    image_logo = url_for(
        'static', filename='profile_pics/' + current_user.img_logo)
    return render_template('rig_corporate.html', title='Corporate Register', image_ntn=image_ntn, image_logo=image_logo, form=form, legend='Corporate Registration Form')


@ auth.route('/account', methods=['GET', 'POST'])
@ login_required
def account():
    form = UpdateAccountForm()
    form.profession.choices = [(profession.id, profession.profession)
                               for profession in Profession.query.all()]
    form.country.choices = [(country.id, country.country)
                            for country in Country.query.all()]
    form.province.choices = [(province.id, province.province)
                             for province in Province.query.all()]
    form.city.choices = [(city.id, city.city) for city in City.query.all()]
    form.districts.choices = [(districts.id, districts.district)
                              for districts in Districts.query.all()]
    form.town.choices = [(town.id, town.town) for town in Town.query.all()]
    form.area.choices = [(area.id, area.area) for area in Areas.query.all()]

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.fname = form.fname.data
        current_user.mname = form.mname.data
        current_user.lname = form.lname.data
        current_user.profession = form.profession.data
        current_user.cnic_num = form.cnic_num.data
        current_user.phone_num = form.phone_num.data
        current_user.country = form.country.data
        current_user.state = form.province.data
        current_user.city = form.city.data
        current_user.districts = form.districts.data
        current_user.town = form.town.data
        current_user.area = form.area.data
        current_user.house = form.house.data
        current_user.street = form.street.data
        db.session.commit()
        flash(
            f'Your account has been updated.', 'success')
        return redirect(url_for('auth.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.fname.data = current_user.fname
        form.mname.data = current_user.mname
        form.lname.data = current_user.lname
        form.profession.data = current_user.profession
        form.cnic_num.data = current_user.cnic_num
        form.phone_num.data = current_user.phone_num
        form.country.data = current_user.country
        form.province.data = current_user.state
        form.city.data = current_user.city
        form.districts.data = current_user.districts
        form.town.data = current_user.town
        form.area.data = current_user.area
        form.house.data = current_user.house
        form.street.data = current_user.street

    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@ auth.route('/province/<get_country_id>')
def provincebycountry(get_country_id):
    province_data = Province.query.filter_by(country_id=get_country_id).all()
    provinceArray = []
    for province in province_data:
        provinceObj = {}
        provinceObj['id'] = province.id
        provinceObj['province'] = province.province
        provinceArray.append(provinceObj)
    return jsonify({'provincelist': provinceArray})


@ auth.route('/city/<get_province>')
def citybystate(get_province):
    city_data = City.query.filter_by(provinces=get_province).all()
    cityArray = []
    for city in city_data:
        cityObj = {}
        cityObj['id'] = city.id
        cityObj['city'] = city.city
        cityArray.append(cityObj)

    return jsonify({'citylist': cityArray})


@ auth.route('/district/<get_city_id>')
def districtbycity(get_city_id):
    district_data = Districts.query.filter_by(cities=get_city_id).all()
    districtArray = []
    for district in district_data:
        districtObj = {}
        districtObj['id'] = district.id
        districtObj['district'] = district.district
        districtArray.append(districtObj)

    return jsonify({'districtlist': districtArray})


@ auth.route('/town/<get_district_id>')
def townbydistrict(get_district_id):
    town_data = Town.query.filter_by(district=get_district_id).all()
    townArray = []
    for town in town_data:
        townObj = {}
        townObj['id'] = town.id
        townObj['town'] = town.town
        townArray.append(townObj)

    return jsonify({'townlist': townArray})


@ auth.route('/area/<get_town_id>')
def areabytown(get_town_id):
    area_data = Areas.query.filter_by(towns=get_town_id).all()
    areaArray = []
    for area in area_data:
        areaObj = {}
        areaObj['id'] = area.id
        areaObj['area'] = area.area
        areaArray.append(areaObj)

    return jsonify({'arealist': areaArray})


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request',
                  sender='noreply@kwickfit.com',
                  recipients=[user.email])
    msg.body = f'''To reset your password, visit the following link:
    {url_for('reset_token', token=token, external=True)}
    if you did not make this request then simply ignore this email and no changes will be made.
    '''
    mail.send(msg)


@ auth.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('auth.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

website/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from .models import Post, User, Neworder
from .forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm, VehicleForm
from flask_login import login_user, current_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash


views = Blueprint('views', __name__)


@views.route('/')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.update_posted.desc()).paginate(page=page, per_page=5)
    neworders = Neworder.query.order_by(
        Neworder.order_posted_date.desc())

    return render_template('home.html', title='Home', posts=posts, neworders=neworders)


@views.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.update_posted.desc()).paginate(page=page, per_page=5)

    return render_template('user_post.html', title='User Posts', posts=posts, user=user)


@views.route('/user/order/<string:username>')
def user_order(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    userorder = Neworder.query.filter_by(author=user).order_by(
        Neworder.order_posted_date.desc()).paginate(page=page, per_page=5)

    return render_template('user_order.html', title='User Orders', userorder=userorder, user=user)


@views.route('/about', methods=['Get', 'POST'])
def about():
    colours = ["White", "Yellow", "Grey", "Red", "Blue", "Black", "Orange"]
    return render_template('about.html', title='About', colours=colours)


@views.route('/newlogin', methods=['GET', 'POST'])
def newlogin():
    if current_user. is_authenticated:
        return redirect(url_for('views.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('views.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')

    return render_template('newlogin.html', title='New Login', form=form)

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link type="text/JavaScript" href="{{ url_for('static', filename='index.js') }}">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

    {% if title %}
    <title>KwickFit - {{ title }}</title>
    {% else %}
    <title>KwickFit</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Kwick Fit</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{url_for('views.home')}}">Home</a>
                        <a class="nav-item nav-link" href="{{url_for('auth.coregister')}}">Become a patner</a>
                        <a class="nav-item nav-link" href="{{url_for('views.about')}}">About</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{url_for('views.home')}}">Home</a>
                        <a class="nav-item nav-link" href="{{url_for('views.about')}}">About</a>
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}

                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if current_user.fname == None %}
                                {{ current_user.username }}
                                {% else %}
                                {% if current_user.mname == None %}
                                {{ current_user.fname }} {{ current_user.lname }}
                                {% else %}
                                {{ current_user.fname }} {{ current_user.mname }} {{ current_user.lname }}
                                {% endif %}
                                {% endif %}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{{url_for('auth.logout')}}">Logout</a>
                                <a class="dropdown-item" href="{{url_for('auth.account')}}">Account</a>
                                <a class="dropdown-item" href="{{url_for('posts.new_post')}}">New Post</a>
                                <a class="dropdown-item" href="{{url_for('vehi.uservehicle')}}">Manage Vehicle</a>
                                <a class="dropdown-item" href="{{url_for('work_order.create_work_order')}}">Work
                                    Order</a>
                                <a class="dropdown-item" href="{{url_for('auth.dashboard')}}">Dashboard</a>
                                <a class="dropdown-item" href="{{url_for('prod.full_prod')}}">Full Product</a>
                                <a class="dropdown-item" href="{{url_for('prod.add_prod')}}">Add Product</a>
                            </div>
                        </div>

                        {% else %}
                        <a class="nav-item nav-link" href="{{url_for('auth.login')}}">Login</a>
                        <a class="nav-item nav-link" href="{{url_for('auth.register')}}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4">
                {% block contentright %}

                {% endblock %}
            </div>

        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>

website/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% for post in posts.items %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('views.user_posts', username=post.author.username)}}">
                {% if post.author.fname == None %}
                {{ post.author.username }}
                {% else %}
                {% if post.author.mname == None %}
                {{ post.author.fname }} {{ post.author.lname }}
                {% else %}
                {{ post.author.fname }} {{ post.author.mname }} {{ post.author.lname }}
                {% endif %}
                {% endif %}
            </a>
            <small class="text-muted">Last update: {{ post.update_posted.strftime('%Y-%m-%d')
                }}</small>
        </div>

        <h5><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title
                }}</a></h5>
        <!-- <div class="text-nowrap" style="width: 38rem;"> -->
        <p class="article-content">{{ post.content }}</p>
        <!-- </div> -->
    </div>
</article>
{% endfor %}


{% for neworder in neworders %}
<article class="media content-section">

    <div class="media-body">
        <img class="rounded-circle article-img"
            src="{{ url_for('static', filename='profile_pics/' + neworder.author.image_file) }}">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('views.user_order', username=neworder.author.username)}}">
                {% if neworder.author.fname == None %}
                {{ neworder.author.username }}
                {% else %}
                {% if neworder.author.mname == None %}
                {{ neworder.author.fname }} {{ neworder.author.lname }}
                {% else %}
                {{ neworder.author.fname }} {{ neworder.author.mname }} {{ neworder.author.lname }}
                {% endif %}
                {% endif %}
            </a>
            <small class="text-muted">{{ neworder.order_posted_date.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('work_order.orderview', order_id=neworder.id) }}">{{
                neworder.order }}</a></h2>


        <p class="article-content">{{ neworder.order_content }}</p>
    </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('views.home', page=page_num)}}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('views.home', page=page_num)}}">{{ page_num }}</a>
{% endif %}

{% else %}
...
{% endif %}

{% endfor %}
{% endblock content %}

website/templates/login.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    {% if title %}
    <title>KwickFit - {{ title }}</title>
    {% else %}
    <title>KwickFit</title>
    {% endif %}

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="{{ url_for('static', filename='css_5_2_3/bootstrap.min.css') }}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='signin.css') }}" rel="stylesheet">
</head>

<body class=" text-center">

    <main class="form-signin w-100 m-auto">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <!-- <div class="alert alert-{{ category }}">
            {{ message }}
        </div> -->
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}

        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <img class="mb-4" src="{{ url_for('static', filename='profile_pics/carpic.png') }}" alt="" width="150"
                height="55">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            <div class="form-floating">
                <!-- {{ form.email.label(class="form-control-label") }} -->
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control") }}
                {% endif %}
                <!-- <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"> -->
                <label for="email">Email address</label>
                <div class="form-floating">
                    <!-- {{ form.password.label(class="form-control-label") }} -->
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                    <!-- <input type="password" class="form-control" id="floatingPassword" placeholder="Password"> -->
                    <label for="password">Password</label>
                </div>

                <div class="checkbox mb-3">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                    <!-- <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label> -->
                </div>
                {{ form.submit(class="w-100 btn btn-primary") }}

                <!-- <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button> -->
                <small class="text-muted ml-2">
                    <a href="#">Forgot Password?</a>
                </small>
                <br>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need An Account? <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up Now</a>
                    </small>
                </div>
                <p class="mt-5 mb-3 text-muted">&copy; Kwick Fit 2017–2022</p>
        </form>

    </main>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
</body>

</html>

website/templates/login_old.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small class="text-muted ml-2">
            <a href="#">Forgot Password?</a>
        </small>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

website/templates/user_post.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-3">Post by {% if user.fname == None %}
    {{ user.username }}
    {% else %}
    {% if user.mname == None %}
    {{ user.fname }} {{ user.lname }}
    {% else %}
    {{ user.fname }} {{ user.mname }} {{ user.lname }}
    {% endif %}
    {% endif %} ({{ posts.total }})</h1>
{% for post in posts.items %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('views.user_posts', username=post.author.username)}}">
                {% if post.author.fname == None %}
                {{ post.author.username }}
                {% else %}
                {% if post.author.mname == None %}
                {{ post.author.fname }} {{ post.author.lname }}
                {% else %}
                {{ post.author.fname }} {{ post.author.mname }} {{ post.author.lname }}
                {% endif %}
                {% endif %}
            </a>
            <small class="text-muted">Last update: {{ post.update_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('views.user_posts', username=user.username, page=page_num)}}">{{ page_num
    }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('views.user_posts',username=user.username, page=page_num)}}">{{
    page_num }}</a>
{% endif %}

{% else %}
...
{% endif %}

{% endfor %}
{% endblock content %}